global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: gateway
    scheme: https
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - qlanka-gateway.redrock-2a740b8b.centralindia.azurecontainerapps.io

  - job_name: identity
    scheme: https
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets:
          - qlanka-identity.redrock-2a740b8b.centralindia.azurecontainerapps.io

  - job_name: service-center
    scheme: https
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets:
          - qlanka-servicecenter.redrock-2a740b8b.centralindia.azurecontainerapps.io

  - job_name: queue
    scheme: https
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - qlanka-queue.redrock-2a740b8b.centralindia.azurecontainerapps.io
